<p>It looks like you are ready to install Canopy3.</p>
<p>Before we get started, we have one security measure. Please create a file named <code>setup.php</code> in your config directory.</p>
<p>Copy and paste the below into the file and save it like so: <code><?=$t->configFile?></code></p>
<?=$t->fileCode?>
<p>You may also copy and paste this into the console:</p>
<?=$t->consoleCode?>
<p>Once you do this, <a href="./">refresh the page</a> to continue.</p>
<div class="alert alert-warning">If you did not expect this screen, check your <code>config/resourcesUrl.php</code> and <code>config/db.php</code> files.</div>
